### ISSUE TITLE
Dev environment set up instructions 

### ISSUE THREAD

**Issue by asifamz** [arun-gupta/kubernetes-aws-workshop#104] opened 2017-10-26 00:31 UTC
Followed mac setup instruction

when trying to start local cluster.

minikube start

Error:
 Error starting host:  Error starting stopped host: docker-machine-driver-xhyve binary needs root owner and uid. See https://github.com/zchee/docker-machine-driver-xhyve#install

**Comment by arun-gupta** [comment] 2017-10-26 01:22
What is the output from `brew cask install minikube`?

What is the output from `minikube version`?

**Comment by asifamz** [comment] 2017-10-26 03:52
i had to do the steps to give root user on xhyve  
i had an earlier minikube when i removed it and updated minikube worked.
the xhyve problem remains

**Comment by arun-gupta** [comment] 2017-10-26 04:01
Can you answer the questions in the comment above?

**Comment by asifamz** [comment] 2017-10-26 04:27
brew cask install minikube
  Installing Cask minikube
Error: It seems there is already a Binary at '/usr/local/bin/minikube'; not linking

 minkube version
minikube version: v0.15.0

**Comment by dalbhanj** [comment] 2017-10-31 19:29
I could not reproduce above issue. 
Asif, can you update minikube to latest version and see if it resolves your issue?
Here are my versions for minikube and kubectl,
$ minikube version
minikube version: v0.23.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by arun-gupta** [comment] 2017-11-03 04:23
@dalbhanj let's keep an eye on this and see if anybody else face this issue as well tomorrow. We should fix this issue with a PR or close it accordingly.

**Closed** 2017-11-06 21:10 UTC
Labels: bug
